"""add_cas_document_flow_and_visa_application

Revision ID: 1f75dbfdd27f
Revises: d970ce70d295
Create Date: 2025-09-10 22:57:31.816452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f75dbfdd27f'
down_revision: Union[str, None] = 'd970ce70d295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_cas_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_uploaded', sa.Boolean(), nullable=True),
    sa.Column('uploaded_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_document_id'], ['application_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_cas_documents_id'), 'application_cas_documents', ['id'], unique=False)
    op.add_column('applications', sa.Column('cas_documents_configured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('cas_documents_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('cas_notes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('visa_application_enabled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'visa_application_enabled_at')
    op.drop_column('applications', 'cas_notes')
    op.drop_column('applications', 'cas_documents_submitted_at')
    op.drop_column('applications', 'cas_documents_configured_at')
    op.drop_index(op.f('ix_application_cas_documents_id'), table_name='application_cas_documents')
    op.drop_table('application_cas_documents')
    # ### end Alembic commands ###
