"""add_offer_letter_email_draft_fields

Revision ID: 54f3f673542c
Revises: ce0b87a51f9c
Create Date: 2025-09-16 00:11:34.303862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f3f673542c'
down_revision: Union[str, None] = 'ce0b87a51f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('offer_letter_email_draft', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('offer_letter_email_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('offer_letter_email_edited_by_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'offer_letter_email_edited_by_admin')
    op.drop_column('applications', 'offer_letter_email_generated_at')
    op.drop_column('applications', 'offer_letter_email_draft')
    # ### end Alembic commands ###
