"""add_visa_document_flow_and_application_fields

Revision ID: 99afbe69a92f
Revises: 1f75dbfdd27f
Create Date: 2025-09-10 23:13:58.141340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99afbe69a92f'
down_revision: Union[str, None] = '1f75dbfdd27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_visa_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_uploaded', sa.Boolean(), nullable=True),
    sa.Column('uploaded_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_document_id'], ['application_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_visa_documents_id'), 'application_visa_documents', ['id'], unique=False)
    op.add_column('applications', sa.Column('visa_documents_configured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('visa_documents_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('visa_applied_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('visa_received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('visa_filename', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('visa_original_filename', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('visa_path', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('visa_size', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('visa_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'visa_notes')
    op.drop_column('applications', 'visa_size')
    op.drop_column('applications', 'visa_path')
    op.drop_column('applications', 'visa_original_filename')
    op.drop_column('applications', 'visa_filename')
    op.drop_column('applications', 'visa_received_at')
    op.drop_column('applications', 'visa_applied_at')
    op.drop_column('applications', 'visa_documents_submitted_at')
    op.drop_column('applications', 'visa_documents_configured_at')
    op.drop_index(op.f('ix_application_visa_documents_id'), table_name='application_visa_documents')
    op.drop_table('application_visa_documents')
    # ### end Alembic commands ###
