"""add_offer_letter_fields_to_applications

Revision ID: c5a397f6d788
Revises: aa3a13712b89
Create Date: 2025-09-09 22:02:08.899089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a397f6d788'
down_revision: Union[str, None] = 'aa3a13712b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('offer_letter_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('offer_letter_received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('offer_letter_filename', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('offer_letter_original_filename', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('offer_letter_path', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('offer_letter_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'offer_letter_size')
    op.drop_column('applications', 'offer_letter_path')
    op.drop_column('applications', 'offer_letter_original_filename')
    op.drop_column('applications', 'offer_letter_filename')
    op.drop_column('applications', 'offer_letter_received_at')
    op.drop_column('applications', 'offer_letter_requested_at')
    # ### end Alembic commands ###
