"""add_interview_enhancements_and_cas_fields

Revision ID: d970ce70d295
Revises: f9ea85745f9a
Create Date: 2025-09-10 22:19:26.801989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd970ce70d295'
down_revision: Union[str, None] = 'f9ea85745f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('interview_location', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('interview_meeting_link', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('interview_result', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('interview_result_notes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('interview_result_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('cas_applied_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('cas_received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('cas_filename', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('cas_original_filename', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('cas_path', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('cas_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cas_size')
    op.drop_column('applications', 'cas_path')
    op.drop_column('applications', 'cas_original_filename')
    op.drop_column('applications', 'cas_filename')
    op.drop_column('applications', 'cas_received_at')
    op.drop_column('applications', 'cas_applied_at')
    op.drop_column('applications', 'interview_result_date')
    op.drop_column('applications', 'interview_result_notes')
    op.drop_column('applications', 'interview_result')
    op.drop_column('applications', 'interview_meeting_link')
    op.drop_column('applications', 'interview_location')
    # ### end Alembic commands ###
