"""add_interview_scheduling_fields

Revision ID: f9ea85745f9a
Revises: c5a397f6d788
Create Date: 2025-09-09 23:36:51.729527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ea85745f9a'
down_revision: Union[str, None] = 'c5a397f6d788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_interview_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_uploaded', sa.Boolean(), nullable=True),
    sa.Column('uploaded_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_document_id'], ['application_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_interview_documents_id'), 'application_interview_documents', ['id'], unique=False)
    op.add_column('applications', sa.Column('interview_documents_configured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('interview_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('interview_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('interview_status', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('interview_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'interview_notes')
    op.drop_column('applications', 'interview_status')
    op.drop_column('applications', 'interview_date')
    op.drop_column('applications', 'interview_scheduled_at')
    op.drop_column('applications', 'interview_requested_at')
    op.drop_column('applications', 'interview_documents_configured_at')
    op.drop_index(op.f('ix_application_interview_documents_id'), table_name='application_interview_documents')
    op.drop_table('application_interview_documents')
    # ### end Alembic commands ###
